Public Class TableName
    Public Const GLAccounts As String = "GLAccounts"
    Public Const GLAccountBudgets As String = "GLAccountBudgets"
    Public Const CostCenters As String = "CostCenters"
    Public Const GLVouchers As String = "GLVouchers"
    Public Const GLVoucherItems As String = "GLVoucherItems"
    Public Const Regions As String = "Regions"
    Public Const PriceList As String = "PriceList"
    Public Const AccessTypes As String = "AccessTypes"
    Public Const Items As String = "Items"
    Public Const ItemUnits As String = "ItemUnits"
    Public Const ItemBarcodes As String = "ItemBarcodes"
    Public Const ItemPricesList As String = "ItemPricesList"
    Public Const ItemItems As String = "ItemItems"
    Public Const ItemAccounts As String = "ItemAccounts"
    Public Const Units As String = "Units"
    Public Const Stores As String = "Stores"
    Public Const ServicePoints As String = "ServicePoints"
    Public Const ItemsClass As String = "ItemsClass"
    Public Const ItemTaxes As String = "ItemTaxes"
End Class
